#!/bin/bash

USER=$(whoami)
DATE=$(date +"%Y-%m-%d %H:%M:%S")

HOSTNAME=$(hostname)
OS=$(lsb_release -d | awk -F"\t" '{print $2}')
UPTIME=$(uptime -p)

CPU=$(lshw -class processor | grep product | awk -F": " '{print $2}')
CPU_SPEED=$(lshw -class processor | grep -m 1 capacity | awk -F": " '{print $2}')
RAM=$(free -h | grep Mem | awk '{print $2}')
DISKS=$(lsblk -o NAME,MODEL,SIZE | grep -E "sd|hd|vd")
VIDEO=$(lshw -class display | grep product | awk -F": " '{print $2}')

FQDN=$(hostname -f)
HOST_ADDRESS=$(hostname -I | awk '{print $1}')
GATEWAY_IP=$(ip r | grep default | awk '{print $3}')
DNS_SERVER=$(nmcli dev show | grep 'IP4.DNS' | awk '{print $2}' | head -n 1)
INTERFACE_NAME=$(ip -o link show | awk -F': ' '{print $2}')
IP_ADDRESS=$(ip -o -f inet addr show | awk '/scope global/ {print $4}')

USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd ",")
DISK_SPACE=$(df -h --output=source,fstype,size,used,avail,pcent,target -x tmpfs -x devtmpfs)
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(uptime | awk -F'load average: ' '{print $2}')
MEMORY_ALLOCATION=$(free -h)
LISTENING_PORTS=$(ss -tuln | grep LISTEN | awk '{print $5}')
UFW_RULES=$(sudo ufw status numbered)

cat <<EOF

System Report generated by $USER, $DATE

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU
Speed: $CPU_SPEED
RAM: $RAM
Disks: 
$DISKS
Video: $VIDEO

Network Information
-------------------
FQDN: $FQDN
Host Address: $HOST_ADDRESS
Gateway IP: $GATEWAY_IP
DNS Server: $DNS_SERVER

Interface Name: $INTERFACE_NAME
IP Address: $IP_ADDRESS

System Status
-------------
Users Logged In: $USERS
Disk Space: 
$DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Memory Allocation: 
$MEMORY_ALLOCATION
Listening Network Ports: 
$LISTENING_PORTS
UFW Rules: 
$UFW_RULES

EOF
